/*
 * File: app/model/CollectionItem.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Recccords.model.CollectionItem', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'recordName'
            },
            {
                name: 'recordLabel'
            },
            {
                name: 'recordArtist'
            },
            {
                name: 'recordYear'
            },
            {
                name: 'recordThumb'
            },
            {
                name: 'discogsId'
            }
        ]
    }
});